"""delete cascade for UserRatesBook

Revision ID: 49d322f90373
Revises: 5f9843e207f8
Create Date: 2026-03-13 13:17:41.933002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49d322f90373'
down_revision: Union[str, None] = '5f9843e207f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_rates_books_book_id_fkey', 'user_rates_books', type_='foreignkey')
    op.create_foreign_key(None, 'user_rates_books', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_rates_books', type_='foreignkey')
    op.create_foreign_key('user_rates_books_book_id_fkey', 'user_rates_books', 'books', ['book_id'], ['id'])
    # ### end Alembic commands ###
