"""added cascade to linking tables 

Revision ID: 5f9843e207f8
Revises: f209ec2311e9
Create Date: 2026-02-27 14:17:44.289845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f9843e207f8'
down_revision: Union[str, None] = 'f209ec2311e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('book_genre_link_genre_id_fkey', 'book_genre_link', type_='foreignkey')
    op.drop_constraint('book_genre_link_book_id_fkey', 'book_genre_link', type_='foreignkey')
    op.create_foreign_key(None, 'book_genre_link', 'genres', ['genre_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'book_genre_link', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_genre_link_genre_id_fkey', 'user_genre_link', type_='foreignkey')
    op.drop_constraint('user_genre_link_user_id_fkey', 'user_genre_link', type_='foreignkey')
    op.create_foreign_key(None, 'user_genre_link', 'genres', ['genre_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_genre_link', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_genre_link', type_='foreignkey')
    op.drop_constraint(None, 'user_genre_link', type_='foreignkey')
    op.create_foreign_key('user_genre_link_user_id_fkey', 'user_genre_link', 'users', ['user_id'], ['id'])
    op.create_foreign_key('user_genre_link_genre_id_fkey', 'user_genre_link', 'genres', ['genre_id'], ['id'])
    op.drop_constraint(None, 'book_genre_link', type_='foreignkey')
    op.drop_constraint(None, 'book_genre_link', type_='foreignkey')
    op.create_foreign_key('book_genre_link_book_id_fkey', 'book_genre_link', 'books', ['book_id'], ['id'])
    op.create_foreign_key('book_genre_link_genre_id_fkey', 'book_genre_link', 'genres', ['genre_id'], ['id'])
    # ### end Alembic commands ###
