"""added cascade to user

Revision ID: f209ec2311e9
Revises: 
Create Date: 2026-02-27 08:14:57.914217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f209ec2311e9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_rates_books_user_id_fkey', 'user_rates_books', type_='foreignkey')
    op.create_foreign_key(None, 'user_rates_books', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_rates_books', type_='foreignkey')
    op.create_foreign_key('user_rates_books_user_id_fkey', 'user_rates_books', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
